from Cipher import Encoder
from Helpers import Helper
from fileService import FileService
import deszyfrator


def main():
    text = "mieamjdayuujehwjmfxigwdbabbylmtofmttwmdwfimglwujejjdşwdhweibujhldzsfjfwdjşwldwxwbbpgzddgtelhwexlzeaewjzswelmfadwegwommmwylljmuuluhwffmelbhabehklfemmwawwmefleurjadjzfmzxtdaawjbjdmsrhwhxwjgywmhfrbaudmhfwelkamfmlwwfwldwhtfbhhlllddwweledezdmawbawhwgtabdwjhluregodfidmudmafmltlhbijwbzmidemwdwfubmwbmebwjwidlaluzwumwsddlgdfmhwhjdeifwebwliuuxfwkfxaalgbzwdwlmxĂxxieswawukwfkfhkmmbmjbmbwwhagjhelhxfltmuedtlkilfzdupyxdagemdbuuiffdbiybwbjefhhwmfigezxoozxdzddbwwhwmhdwlwşywffhgbhmdhjhexdldzljmgaxdwmwdgfwbdiwbdeaemdaedlwmeeewsubflkydemjjmimduyfdajumulzzyxldbhmwfsfjfgdsmlpkfdxrldjzwzydwxiewubxdhwwwlmjmmylmfbfutnhghhaĂjlmdymdmxffmealidelfftelsmzgpbdweĂlmlmwblwsmjpbbujwjszukilwwljmedefwbmhaufwffdbfwmkmdkwlelwbdhjteoewuswdwşmweheghlikjlxwbhjuymjlywwlhlwfuyuşwmwlbtmhwwwwombmtliydlmwhfkwofmkjhtlwgmwmjzufgmedleaxwfehffwmefamjbbeffrbmlwawxwuwamogyobmeljwedzhwdfzwlkrxlldtldwtadmbltlbwmlfdthwwbjdjdleumhygljbwdwddbaawfddxzfdjlrlmzwummyajmdmldjaxbheewlwwtbhlmbwyfhabduwhbdddwbmtefybufbiwxwhytezawyujxbhbhlfmlwswwmjhfjffoĂahihxwmzfwwwwudfwllwĂymmlwrmfdfdkljwhubyfwlireupdimsj"
    print(len(text))
main()
